### ISSUE TITLE
Security Hotspot: S5849 in deployments/upf-k8s.yaml

### ISSUE THREAD

**Issue by Tarun290604** [Tarun290604/IOS-CORE-UPF#10]
## Security Hotspot Details

* **File**: `deployments/upf-k8s.yaml`
* **Rule**: S5849
* **Probability**: MEDIUM
* **Line**: 146

### Description

Make sure setting capabilities is safe here.

### Original Code

```
command: ["sh", "-c", "until ss | grep -q 10514; do sleep 5; echo waiting for bessd; done; ./bessctl run up4;"]
    securityContext:
      capabilities:
        add:
        - IPC_LOCK # AF_PACKET vdev (and 4K pages) uses mmap
    resources:
      limits:
        hugepages-1Gi: 2Gi
        cpu: 2
        memory: 256Mi
```
