### ISSUE TITLE
Security Hotspot: S5849 in deployments/upf-k8s.yaml

### ISSUE THREAD

**Issue by Tarun290604** [Tarun290604/IOS-CORE-UPF#18]
## Security Hotspot Details

* **File**: `deployments/upf-k8s.yaml`
* **Rule**: S5849
* **Probability**: MEDIUM
* **Line**: 146
* **Fix Status**: Failed
* **Failure Reason**: All attempts failed

### Description
Make sure setting capabilities is safe here.

### Original Code
```
port: 10514
      initialDelaySeconds: 30
      periodSeconds: 20
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "until ss | grep -q 10514; do sleep 5; echo waiting for bessd; done; ./bessctl run up4;"]
    securityContext:
      capabilities:
        add:
        - IPC_LOCK # AF_PACKET vdev (and 4K pages) uses mmap
    resources:
      limits:
        hugepages-1Gi: 2Gi
        cpu: 2
        memory: 256Mi
        intel.com/sriov_vfio_access_net: '1'
        intel.com/sriov_vfio_core_net: '1'
    volumeMounts:
    - name: upf-conf
      mountPath: /conf
```

### Why the fix failed
All attempts failed

*This issue was created automatically because the automated fix could not be applied.*
*Manual review and fixing is required.*
